import { AbilityDef, AbilityTrigger, TargetingRule } from '../../types';

export const ALL_ABILITIES: AbilityDef[] = [
  {
    id: 'shield',
    nameKey: 'ability.shield.name',
    descriptionKey: 'ability.shield.description',
    cost: 2,
    maxCharges: 1,
    triggerType: AbilityTrigger.OnBeingCaptured,
    targetingRule: TargetingRule.None,
    icon: '🛡️',
  },
  {
    id: 'teleport',
    nameKey: 'ability.teleport.name',
    descriptionKey: 'ability.teleport.description',
    cost: 3,
    maxCharges: 1,
    triggerType: AbilityTrigger.Active,
    targetingRule: TargetingRule.AnyEmptySquare,
    icon: '✨',
  },
  {
    id: 'double-move',
    nameKey: 'ability.doubleMove.name',
    descriptionKey: 'ability.doubleMove.description',
    cost: 3,
    maxCharges: 1,
    triggerType: AbilityTrigger.Active,
    targetingRule: TargetingRule.None,
    icon: '⚡',
  },
  {
    id: 'freeze',
    nameKey: 'ability.freeze.name',
    descriptionKey: 'ability.freeze.description',
    cost: 2,
    maxCharges: 2,
    triggerType: AbilityTrigger.OnCapture,
    targetingRule: TargetingRule.AdjacentEnemy,
    icon: '❄️',
  },
  {
    id: 'resurrect',
    nameKey: 'ability.resurrect.name',
    descriptionKey: 'ability.resurrect.description',
    cost: 4,
    maxCharges: 1,
    triggerType: AbilityTrigger.Active,
    targetingRule: TargetingRule.CapturedFriendly,
    icon: '💫',
  },
  {
    id: 'range-attack',
    nameKey: 'ability.rangeAttack.name',
    descriptionKey: 'ability.rangeAttack.description',
    cost: 2,
    maxCharges: 1,
    triggerType: AbilityTrigger.Active,
    targetingRule: TargetingRule.SquareInRange,
    icon: '🎯',
  },
  {
    id: 'swap',
    nameKey: 'ability.swap.name',
    descriptionKey: 'ability.swap.description',
    cost: 2,
    maxCharges: 1,
    triggerType: AbilityTrigger.Active,
    targetingRule: TargetingRule.FriendlyPiece,
    icon: '🔄',
  },
  {
    id: 'mine',
    nameKey: 'ability.mine.name',
    descriptionKey: 'ability.mine.description',
    cost: 2,
    maxCharges: 2,
    triggerType: AbilityTrigger.OnMove,
    targetingRule: TargetingRule.None,
    icon: '💣',
  },
  {
    id: 'scout',
    nameKey: 'ability.scout.name',
    descriptionKey: 'ability.scout.description',
    cost: 1,
    maxCharges: 2,
    triggerType: AbilityTrigger.Active,
    targetingRule: TargetingRule.None,
    icon: '🔍',
  },
  {
    id: 'berserk',
    nameKey: 'ability.berserk.name',
    descriptionKey: 'ability.berserk.description',
    cost: 3,
    maxCharges: 2,
    triggerType: AbilityTrigger.OnCapture,
    targetingRule: TargetingRule.None,
    icon: '🔥',
  },
  {
    id: 'fortify',
    nameKey: 'ability.fortify.name',
    descriptionKey: 'ability.fortify.description',
    cost: 2,
    maxCharges: 1,
    triggerType: AbilityTrigger.Passive,
    targetingRule: TargetingRule.None,
    icon: '🏰',
  },
  {
    id: 'poison',
    nameKey: 'ability.poison.name',
    descriptionKey: 'ability.poison.description',
    cost: 2,
    maxCharges: 1,
    triggerType: AbilityTrigger.OnBeingCaptured,
    targetingRule: TargetingRule.None,
    icon: '☠️',
  },
  {
    id: 'shadow-step',
    nameKey: 'ability.shadowStep.name',
    descriptionKey: 'ability.shadowStep.description',
    cost: 2,
    maxCharges: 2,
    triggerType: AbilityTrigger.Active,
    targetingRule: TargetingRule.AdjacentEnemy,
    icon: '👤',
  },
  {
    id: 'iron-will',
    nameKey: 'ability.ironWill.name',
    descriptionKey: 'ability.ironWill.description',
    cost: 1,
    maxCharges: -1,
    triggerType: AbilityTrigger.Passive,
    targetingRule: TargetingRule.None,
    icon: '🦾',
  },
];

export function getAbilityById(id: string): AbilityDef | undefined {
  return ALL_ABILITIES.find(a => a.id === id);
}
